In [1]:
import numpy as np
import pandas as pd



In [2]:
ar = np.random.randint(1,20,size=(4,5),dtype=int)
ar = ar.reshape(5,4)
ar

array([[18,  8,  8,  5],
       [17,  2,  9, 16],
       [17, 19, 11, 12],
       [19, 12, 16, 12],
       [ 8,  4, 15, 16]])

In [3]:
dataframe =  pd.DataFrame(data=ar,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col14'],dtype=int)

dataframe.head(5)

col1  col2  col3  col14
row1    18     8     8      5
row2    17     2     9     16
row3    17    19    11     12
row4    19    12    16     12
row5     8     4    15     16

In [4]:
X = dataframe.iloc[:,:-1].values
X

array([[18,  8,  8],
       [17,  2,  9],
       [17, 19, 11],
       [19, 12, 16],
       [ 8,  4, 15]])

In [5]:
dataframe[['col1','col2']]

col1  col2
row1    18     8
row2    17     2
row3    17    19
row4    19    12
row5     8     4

In [6]:
dataframe.describe()

col1      col2       col3      col14
count   5.000000   5.00000   5.000000   5.000000
mean   15.800000   9.00000  11.800000  12.200000
std     4.438468   6.78233   3.563706   4.494441
min     8.000000   2.00000   8.000000   5.000000
25%    17.000000   4.00000   9.000000  12.000000
50%    17.000000   8.00000  11.000000  12.000000
75%    18.000000  12.00000  15.000000  16.000000
max    19.000000  19.00000  16.000000  16.000000

In [7]:
dataset =  pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/Car_Purchasing_Data.csv',encoding='ISO-8859-1')
dataset.head(7)

Customer Name  ... Car Purchase Amount
0    Martina Avila  ...         35321.45877
1    Harlan Barnes  ...         45115.52566
2  Naomi Rodriquez  ...         42925.70921
3  Jade Cunningham  ...         67422.36313
4     Cedric Leach  ...         55915.46248
5     Carla Hester  ...         56611.99784
6   Griffin Rivera  ...         28925.70549

[7 rows x 9 columns]

In [8]:
dataset.describe()

Gender         Age  ...       Net Worth  Car Purchase Amount
count  500.000000  500.000000  ...      500.000000           500.000000
mean     0.506000   46.241674  ...   431475.713625         44209.799218
std      0.500465    7.978862  ...   173536.756340         10773.178744
min      0.000000   20.000000  ...    20000.000000          9000.000000
25%      0.000000   40.949969  ...   299824.195900         37629.896040
50%      1.000000   46.049901  ...   426750.120650         43997.783390
75%      1.000000   51.612263  ...   557324.478725         51254.709517
max      1.000000   70.000000  ...  1000000.000000         80000.000000

[8 rows x 6 columns]

## JSON Test with Pandas


In [9]:
df =  pd.read_json('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/iris.json')

X1 = df.iloc[:,:-1].values

X1.shape

(150, 4)

In [10]:
X1

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/iris.csv')

In [12]:
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/iris.csv')

df1.to_json(orient='records')

'[{"Unnamed: 0":0,"sepalLength":5.1,"sepalWidth":3.5,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":1,"sepalLength":4.9,"sepalWidth":3.0,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":2,"sepalLength":4.7,"sepalWidth":3.2,"petalLength":1.3,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":3,"sepalLength":4.6,"sepalWidth":3.1,"petalLength":1.5,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":4,"sepalLength":5.0,"sepalWidth":3.6,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":5,"sepalLength":5.4,"sepalWidth":3.9,"petalLength":1.7,"petalWidth":0.4,"species":"setosa"},{"Unnamed: 0":6,"sepalLength":4.6,"sepalWidth":3.4,"petalLength":1.4,"petalWidth":0.3,"species":"setosa"},{"Unnamed: 0":7,"sepalLength":5.0,"sepalWidth":3.4,"petalLength":1.5,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":8,"sepalLength":4.4,"sepalWidth":2.9,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"},{"Unnamed: 0":9,"sepalLength":4.9,"sepalWidt

In [13]:
sample_table_url = 'https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data'

df_table = pd.read_html(sample_table_url,match='world')

df_table = df_table[0].iloc[:-3,1:-1]

df_table

Location[a]    Cases[b] Deaths[c]  Recov.[d]
                           World[e] 139,120,305 2,986,951 79,225,051
0                  United States[f]    31682046    570531    No data
1                             India    14074564    173123   12429564
2                            Brazil    13758093    365954   12236295
3                         France[g]     5187879    100073    No data
4                         Russia[h]     4684148    104795    4310557
..                              ...         ...       ...        ...
233                Marshall Islands           4         0          4
234                  American Samoa           4         0          3
235                           Samoa           4         0          2
236                         Vanuatu           3         0          1
237  Federated States of Micronesia           1         0          1

[238 rows x 4 columns]

In [14]:
df_table.to_excel('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/covid.xlsx')

In [15]:
df_table.to_pickle('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/covid_pickle')

df_p = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/ML DL and NLP Examples/Example1/covid_pickle')


In [16]:
df_p

Location[a]    Cases[b] Deaths[c]  Recov.[d]
                           World[e] 139,120,305 2,986,951 79,225,051
0                  United States[f]    31682046    570531    No data
1                             India    14074564    173123   12429564
2                            Brazil    13758093    365954   12236295
3                         France[g]     5187879    100073    No data
4                         Russia[h]     4684148    104795    4310557
..                              ...         ...       ...        ...
233                Marshall Islands           4         0          4
234                  American Samoa           4         0          3
235                           Samoa           4         0          2
236                         Vanuatu           3         0          1
237  Federated States of Micronesia           1         0          1

[238 rows x 4 columns]